# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

gem 'bootsnap', require: false
gem 'jsonapi-serializer', '~> 2.2.0'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rack-cors', '~> 1.1.1'
gem 'rails', '~> 7.0.4', '>= 7.0.4.2'
gem 'redis', '~> 5.0.6'
gem 'sidekiq', '~> 7.0'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development do
  gem 'rubocop', '~> 1.45', require: false
end

group :development, :test do
  gem 'awesome_print', '~> 1.9.2'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 6.2.0'
end

group :test do
  gem 'rspec-rails', '~> 6.0.1'
  gem 'shoulda-matchers', '~> 5.3.0'
end
